### ISSUE TITLE
The ch1 sample stops with error

### ISSUE THREAD

**Issue by mike-holcomb** [royosherove/aout3-samples#2]
The linter appears to run over all of the folders in the project.  The command `npm run ch1` fails with an error.  Here is the log:

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/mike/.nvm/versions/node/v13.1.0/bin/node',
1 verbose cli   '/Users/mike/.nvm/versions/node/v13.1.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ch1'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v13.1.0
4 verbose run-script [ 'prech1', 'ch1', 'postch1' ]
5 info lifecycle aout3-samples@1.0.0~prech1: aout3-samples@1.0.0
6 info lifecycle aout3-samples@1.0.0~ch1: aout3-samples@1.0.0
7 verbose lifecycle aout3-samples@1.0.0~ch1: unsafe-perm in lifecycle true
8 verbose lifecycle aout3-samples@1.0.0~ch1: PATH: [omit]
9 verbose lifecycle aout3-samples@1.0.0~ch1: CWD: /Users/mike/projects/aout3-samples
10 silly lifecycle aout3-samples@1.0.0~ch1: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'semistandard --fix && node ./ch1/custom-test-phase1.js && node ./ch1/custom-test-phase2.js && node ./ch1/custom-test-phase3.js'
10 silly lifecycle ]
11 silly lifecycle aout3-samples@1.0.0~ch1: Returned: code: 1  signal: null
12 info lifecycle aout3-samples@1.0.0~ch1: Failed to exec ch1 script
13 verbose stack Error: aout3-samples@1.0.0 ch1: `semistandard --fix && node ./ch1/custom-test-phase1.js && node ./ch1/custom-test-phase2.js && node ./ch1/custom-test-phase3.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/mike/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/mike/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid aout3-samples@1.0.0
15 verbose cwd /Users/mike/projects/aout3-samples
16 verbose Darwin 18.6.0
17 verbose argv "/Users/mike/.nvm/versions/node/v13.1.0/bin/node" "/Users/mike/.nvm/versions/node/v13.1.0/bin/npm" "run" "ch1"
18 verbose node v13.1.0
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error aout3-samples@1.0.0 ch1: `semistandard --fix && node ./ch1/custom-test-phase1.js && node ./ch1/custom-test-phase2.js && node ./ch1/custom-test-phase3.js`
22 error Exit status 1
23 error Failed at the aout3-samples@1.0.0 ch1 script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Here is a portion of what prints to stdout:
> semistandard: Semicolons For All! (https://github.com/Flet/semistandard)
  /Users/mike/projects/aout3-samples/ch2/__tests__/hellojest.test.js:1:1: 'test' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/hellojest.test.js:2:3: 'expect' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:3:1: 'describe' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:4:3: 'test' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:6:5: 'expect' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:8:3: 'test' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:10:5: 'expect' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:12:3: 'test' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:14:5: 'expect' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:18:1: 'describe' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:19:3: 'test' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:21:5: 'expect' is not defined.
  /Users/mike/projects/aout3-samples/ch2/__tests__/password-rules.spec.js:24:3: 'test' is not defined.

**Comment by vincentjocodes** [comment]
Also having this same issue. Can you please merge the PR in? @royosherove. Thanks.
